# Generated by Django 4.0.6 on 2022-07-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askerbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='login',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
